name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Go to Folder
      run: cd /var/www/laravel-template || exit
      shell: bash
    - name: Run script file
      run: |
        chmod +x deploy.sh
        deploy.sh
      shell: bash

