name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
#  build:
#    runs-on: self-hosted
#    steps:
#      - uses: actions/checkout@v2
#      - name: Copy .env
#        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
#      - name: Install Dependencies
#        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
#      - name: Generate key
#        run: php artisan key:generate
#      - name: Directory Permissions
#        run: chmod -R 777 storage bootstrap/cache
#      - name: Create Database
#        run: |
#          mkdir -p database
#          touch database/database.sqlite
#
#  test:
#    needs: build
#    runs-on: self-hosted
#    steps:
#      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
#        with:
#          php-version: '8.0'
#      - name: Execute tests (Unit and Feature tests) via PHPUnit
#        env:
#          DB_CONNECTION: sqlite
#          DB_DATABASE: database/database.sqlite
#        run: vendor/bin/phpunit

  deploy:
#    needs: test
    runs-on: self-hosted
    env:
      workdir: /var/www/laravel-template/

    steps:
      - uses: actions/checkout@v2
      - name: Change Group
        run: sudo chown -R $(id -u):$(id -g) .
        working-directory: ${{env.workdir}}
      - name: Put Down
        run: php artisan down --no-interaction
        working-directory: ${{env.workdir}}
      - name: Update folder
        run: git pull origin main
        working-directory: ${{env.workdir}}
      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
        working-directory: ${{env.workdir}}
      - name: Install Node Dependencies
        run: npm install
        working-directory: ${{env.workdir}}
      - name: Build assets
        run: npm run prod
        working-directory: ${{env.workdir}}
      - name: Run migration
        run: php artisan migrate --force
        working-directory: ${{env.workdir}}
      - name: Optimize
        run: php artisan optimize
        working-directory: ${{env.workdir}}
      - name: Put Up
        run: php artisan up
        working-directory: ${{env.workdir}}
#      - name: Change Group
#        run: chown -R www-data:www-data .
#        working-directory: ${{env.workdir}}


