name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Run script file
      run: |
        chmod +x ./deploy.sh
        ./deploy.sh
      shell: bash

