name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Teste
      run: ls
    - name: Go to dir
      run: cd /home/leandro
    - name: make dir
      run: mkdir teste
   
