name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:

    runs-on: self-hosted

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - name: Backup storage
      run: sudo chmod -R 777 storage && sudo mv storage /home/leandro/storage
    - uses: actions/checkout@v2
    - name: Copy .env
      run: ln -s /home/leandro/.env .env
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Restore storage
      run: sudo mv /home/leandro/storage storage
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Directory Group
      run: sudo chown -R www-data:www-data .
    - name: Run migrations
      run: (php artisan migrate --force) || (php artisan migrate:rollback)
    - name: Link storage
      run: php artisan storage:link
    - name: Optimize
      run: php artisan optimize
#     - name: NPM install
#       run: npm install
#     - name: Generate assets
#       run: npm run prod

